source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

#6.64,6.66
gem 'kaminari', '~> 0.15.1'
gem 'kaminari-bootstrap', '~> 3.0.1'
#6.67,rails 4.2では動作しないので最新版にした
gem 'ransack', '~> 1.7.0'
#6.71
gem 'carrierwave', '0.10.0'
#6.76
gem 'mini_magick', '~> 3.7.0'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
	#7.4
	gem 'rspec-rails', '~> 3.0'
	gem 'rspec-core', '~> 3.0'
	gem 'rspec-expectations', '~> 3.0'
	gem 'rspec-mocks', '~> 3.0'
	gem 'rspec-support', '~> 3.0'
	#7.9
	gem 'factory_girl_rails', '~> 4.4.1'
end

#7.8
group :test do
	gem 'shoulda-matchers', '~> 2.6.0'
	#7.18
	gem 'capybara', '~> 2.2.1'
	#7.21
	gem 'poltergeist', '~> 1.5.0'
	gem 'database_cleaner', '~> 1.2.0'
end

#6.4
gem 'omniauth', '~> 1.2.1'
gem 'omniauth-twitter', '~>1.0.1'